environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -e .[dev]"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"
